### PR TITLE
add SWESAR

### PR DESCRIPTION
**Pull request by ShihengDuan**
SWESAR config file.

### CODE REVIEW

**Comment by cjrd** [comment]
Did you verify the data is in the expected format/range/etc?

**Comment by cjrd** [comment]
Please create a similar proof-of-correctness =)
[grace-fo-plot.ipynb](https://github.com/bair-climate-initiative/metaearth/blob/main/nbs/grace-fo-plot.ipynb)

**Comment by ShihengDuan** [comment]
I've added a notebook in `demo-nbs/SWESAR+UAVSAR.ipynb`. Does that help?

**Comment by cjrd** [comment]
Some comments:

1. Add any new nb dependencies under `setup.cfg:tests`: [metaearth](https://github.com/bair-climate-initiative/metaearth)/setup.cfg
2. Download 1 example data in the notebook

**Comment by ShihengDuan** [comment]
Update the notebook. Now it downloads data and plots some figures. Need to install GDAL by conda as we discussed.

**Pull request closed without merging**
